import './globals.css'
import { Montserrat} from 'next/font/google'

const montserratRegular = Montserrat({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Dadilja Melisa',
  description: 'Generated by create next app',
  // Google description
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserratRegular.className}>{children}</body>
    </html>
  )
}
