import './globals.css';
import { Montserrat} from 'next/font/google';
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';

const montserratRegular = Montserrat({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Dadilja Melisa',
  description: 'Generated by create next app',
  // Google description
}

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'sr'}];
}

export default async function LocaleLayout({children, params: {locale}}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
      <html lang={locale}>
        <body className={montserratRegular.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
          </body>
      </html>
  )
}
