import "./globals.css";
import { Montserrat } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";

const montserratRegular = Montserrat({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
	title: "Dadilja Melisa",
	description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
	let messages;
	const locale = useLocale();

	if (params.locale !== locale) {
		notFound();
	} else {
		messages = (await import(`../../messages/${locale}.json`)).default;
	}

	return (
		<html lang={locale}>
			<body className={montserratRegular.className}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
